# Generated by Django 4.2.6 on 2023-12-04 19:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("REP_App", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="property_profile",
            name="property_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalidname",
                        message="Name should be only in letters",
                        regex="^[a-zA-Z\\s]*$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tenant_profile",
            name="document",
            field=models.FileField(upload_to="property_documents/"),
        ),
        migrations.AlterField(
            model_name="tenant_profile",
            name="tenant_name",
            field=models.CharField(
                max_length=100,
                validators=[
                    django.core.validators.RegexValidator(
                        code="invalidname",
                        message="Name should be only in letters",
                        regex="^[a-zA-Z\\s]*$",
                    )
                ],
            ),
        ),
    ]
