# Generated by Django 4.2.6 on 2023-12-05 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("REP_App", "0002_alter_property_profile_property_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant_profile",
            name="agreementend_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tenant_profile",
            name="monthly_rent",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="tenant_profile",
            name="monthly_rent_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="tenant_rental_info",
        ),
    ]
