# Generated by Django 4.2.6 on 2023-12-05 05:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("REP_App", "0003_tenant_profile_agreementend_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant_profile",
            name="document",
            field=models.FileField(
                blank=True, null=True, upload_to="property_documents/"
            ),
        ),
    ]
